# Generated by Django 4.2.6 on 2023-11-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAppointment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='typeOfAppointment',
            field=models.CharField(choices=[('G', 'General Healthcare'), ('V', 'Vaccination'), ('C', 'Consultation'), ('P', 'Prenatal'), ('F', 'Family Planning'), ('B', 'Behavioral Healthcare'), ('L', 'Laboratory'), ('D', 'Dental Care'), ('T', 'Physical/Occupational Therapy'), ('M', 'Pharmaceutical Care'), ('N', 'Nutritional Support')], default='G', max_length=1),
        ),
    ]
