# Generated by Django 4.2.6 on 2023-11-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAppointment', '0003_appointment_typeofappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentStatus',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
