# Generated by Django 4.2.6 on 2023-11-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAppointment', '0004_alter_appointment_appointmentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dateOfApproval',
            field=models.DateField(null=True),
        ),
    ]
