# Generated by Django 4.2.6 on 2023-10-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrganizeEvent', '0001_initial'),
        ('CreateAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='approve_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OrganizeEvent.event'),
        ),
    ]
